[project]
name = "msteams_webhooks"
version = "0.0.1"
authors = [
  { name="Austin de Coup-Crank", email="austindcc@gmail.com" },
]
description = "A modern Python API for sending messages to Microsoft Teams using webhooks."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "httpx >= 0.24.1",
]

[project.urls]
"Homepage" = "https://github.com/decoupca/msteams_webhooks"
"Bug Tracker" = "https://github.com/decoupca/msteams_webhooks/issues"

[tool.isort]
profile = "black"