name: Test Suite

on: [push, pull_request, workflow_dispatch]

jobs:
  test_suite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: wntrblm/nox@2023.04.22
        with:
            python-versions: "3.9, 3.10, 3.11"
      - name: Run nox
        run: nox