name: Unit Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Set up test environment
        run: |
          pip install --upgrade pip
          pip install nox
      - name: Run nox
        run: nox